# Generated by Django 4.2.7 on 2023-12-08 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_atividades', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atividades',
            new_name='Atividade',
        ),
    ]
