# Generated by Django 5.0 on 2023-12-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_atividades', '0002_rename_atividades_atividade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividade',
            old_name='realizado',
            new_name='atividades',
        ),
    ]
